import type { MCP, Agent, GovernancePolicy } from './types'
export { agentBlueprints, dlpPolicies, agentTraces, approvalRequests, iqSignals } from './data/governance'

export const mcpCategories = [
  'All Categories',
  'AI',
  'Analytics',
  'CRM',
  'Database',
  'DevTools',
  'Infrastructure',
  'Logging',
  'Monitoring',
  'Observability',
  'Productivity',
  'Security',
  'Storage',
] as const

// Map for backwards compatibility
export const mcpServers: MCP[] = [
  {
    id: 'axiom-mcp',
    name: 'Axiom',
    description: 'Logs, functions, and Web Vitals insights for full-stack observability',
    shortDescription: 'Full-stack observability platform',
    category: 'Logging',
    provider: 'Axiom',
    version: '2.4.1',
    downloads: 15420,
    rating: 4.8,
    ratingCount: 342,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-01-28',
    capabilities: ['Log Ingestion', 'Query Analytics', 'Dashboards', 'Alerting'],
    dataClassification: 'internal',
    icon: 'activity',
    tags: ['logging', 'observability', 'analytics', 'monitoring'],
    isInstalled: true,
  },
  {
    id: 'baseline-mcp',
    name: 'Baseline',
    description: 'Search, query and alert on application logs with intelligent filtering',
    shortDescription: 'Log search and alerting',
    category: 'Logging',
    provider: 'Baseline',
    version: '3.1.0',
    downloads: 8932,
    rating: 4.9,
    ratingCount: 287,
    status: 'pending',
    complianceLevel: 'high',
    lastUpdated: '2026-01-25',
    capabilities: ['Log Search', 'Alerting', 'Dashboards', 'Integrations'],
    dataClassification: 'confidential',
    icon: 'search',
    tags: ['logging', 'search', 'alerts', 'monitoring'],
    isInstalled: false,
  },
  {
    id: 'betterstack-mcp',
    name: 'Better Stack',
    description: 'Query logs like you query your database with powerful SQL-like syntax',
    shortDescription: 'SQL-powered log querying',
    category: 'Logging',
    provider: 'Better Stack',
    version: '1.8.2',
    downloads: 12543,
    rating: 4.7,
    ratingCount: 198,
    status: 'active',
    complianceLevel: 'medium',
    lastUpdated: '2026-01-30',
    capabilities: ['SQL Queries', 'Log Analytics', 'Uptime Monitoring', 'Incident Management'],
    dataClassification: 'internal',
    icon: 'terminal',
    tags: ['logging', 'sql', 'uptime', 'incidents'],
    isInstalled: true,
  },
  {
    id: 'graphjson-mcp',
    name: 'GraphJSON',
    description: 'Slice, dice and visualize your logs with interactive graph interfaces',
    shortDescription: 'Visual log exploration',
    category: 'Logging',
    provider: 'GraphJSON',
    version: '2.2.0',
    downloads: 9876,
    rating: 4.6,
    ratingCount: 156,
    status: 'pending',
    complianceLevel: 'medium',
    lastUpdated: '2026-01-22',
    capabilities: ['Visualization', 'JSON Parsing', 'Graph Analytics', 'Export'],
    dataClassification: 'internal',
    icon: 'bar-chart',
    tags: ['visualization', 'json', 'graphs', 'analytics'],
    isInstalled: false,
  },
  {
    id: 'logalert-mcp',
    name: 'Logalert',
    description: 'Easily set up alerts from your logs with intelligent anomaly detection',
    shortDescription: 'Smart log alerting',
    category: 'Logging',
    provider: 'Logalert',
    version: '4.0.1',
    downloads: 18234,
    rating: 4.8,
    ratingCount: 423,
    status: 'pending',
    complianceLevel: 'high',
    lastUpdated: '2026-01-29',
    capabilities: ['Anomaly Detection', 'Custom Alerts', 'Integrations', 'Escalation'],
    dataClassification: 'internal',
    icon: 'bell',
    tags: ['alerts', 'anomaly', 'notifications', 'monitoring'],
    isInstalled: false,
  },
  {
    id: 'logflare-mcp',
    name: 'Logflare',
    description: 'Search, charts and alerts for logs with real-time streaming',
    shortDescription: 'Real-time log streaming',
    category: 'Logging',
    provider: 'Logflare',
    version: '1.5.3',
    downloads: 7654,
    rating: 4.5,
    ratingCount: 134,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-01-20',
    capabilities: ['Streaming', 'Search', 'Charts', 'Alerts'],
    dataClassification: 'confidential',
    icon: 'zap',
    tags: ['streaming', 'real-time', 'search', 'charts'],
    isInstalled: false,
  },
  {
    id: 'sematext-mcp',
    name: 'Sematext Logs',
    description: 'Send logs to Sematext for easy debugging and comprehensive analysis',
    shortDescription: 'Log debugging and analysis',
    category: 'Logging',
    provider: 'Sematext',
    version: '2.1.0',
    downloads: 21345,
    rating: 4.7,
    ratingCount: 512,
    status: 'pending',
    complianceLevel: 'medium',
    lastUpdated: '2026-01-27',
    capabilities: ['Log Collection', 'Debugging', 'Analysis', 'Correlation'],
    dataClassification: 'internal',
    icon: 'file-text',
    tags: ['logging', 'debugging', 'analysis', 'apm'],
    isInstalled: false,
  },
  {
    id: 'mongodb-mcp',
    name: 'MongoDB Atlas',
    description: 'Connect and query MongoDB collections with intelligent context awareness',
    shortDescription: 'MongoDB database integration',
    category: 'Database',
    provider: 'MongoDB',
    version: '3.0.2',
    downloads: 11234,
    rating: 4.9,
    ratingCount: 289,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-01-26',
    capabilities: ['Queries', 'Aggregation', 'Indexing', 'Atlas Search'],
    dataClassification: 'confidential',
    icon: 'database',
    tags: ['mongodb', 'database', 'nosql', 'atlas'],
    isInstalled: true,
  },
  {
    id: 'github-mcp',
    name: 'GitHub',
    description: 'Interact with GitHub repositories for automation, insights, and code intelligence',
    shortDescription: 'GitHub repository integration',
    category: 'DevTools',
    provider: 'GitHub',
    version: '2.0.0',
    downloads: 25678,
    rating: 4.8,
    ratingCount: 634,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-01-31',
    capabilities: ['Repository Management', 'Pull Requests', 'Issues', 'Actions'],
    dataClassification: 'confidential',
    icon: 'git-branch',
    tags: ['github', 'git', 'code', 'repositories'],
    isInstalled: true,
  },
  {
    id: 'vercel-mcp',
    name: 'Vercel Analytics',
    description: 'Privacy-friendly, first-party analytics for web applications',
    shortDescription: 'Web analytics platform',
    category: 'Analytics',
    provider: 'Vercel',
    version: '1.2.1',
    downloads: 4532,
    rating: 4.4,
    ratingCount: 87,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-01-18',
    capabilities: ['Page Views', 'Web Vitals', 'Custom Events', 'Funnels'],
    dataClassification: 'restricted',
    icon: 'trending-up',
    tags: ['analytics', 'web-vitals', 'performance', 'vercel'],
    isInstalled: true,
  },
  {
    id: 'supabase-mcp',
    name: 'Supabase',
    description: 'Open source Firebase alternative with Postgres database and auth',
    shortDescription: 'Backend-as-a-service',
    category: 'Database',
    provider: 'Supabase',
    version: '1.9.0',
    downloads: 16789,
    rating: 4.6,
    ratingCount: 378,
    status: 'active',
    complianceLevel: 'medium',
    lastUpdated: '2026-01-24',
    capabilities: ['Database', 'Authentication', 'Storage', 'Edge Functions'],
    dataClassification: 'internal',
    icon: 'database',
    tags: ['supabase', 'postgres', 'auth', 'storage'],
    isInstalled: false,
  },
  {
    id: 'neon-mcp',
    name: 'Neon',
    description: 'Serverless Postgres with branching, autoscaling, and bottomless storage',
    shortDescription: 'Serverless Postgres',
    category: 'Database',
    provider: 'Neon',
    version: '2.3.1',
    downloads: 13456,
    rating: 4.7,
    ratingCount: 298,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-01-23',
    capabilities: ['Branching', 'Autoscaling', 'Point-in-time Recovery', 'Connection Pooling'],
    dataClassification: 'confidential',
    icon: 'database',
    tags: ['postgres', 'serverless', 'database', 'neon'],
    isInstalled: false,
  },
  {
    id: 'workiq-mail-mcp',
    name: 'Work IQ Mail',
    description: 'Read, search, and manage email via Microsoft Graph Mail APIs — thread analysis, summarization, and action item extraction powered by Work IQ',
    shortDescription: 'Email via Graph + Work IQ',
    category: 'Productivity',
    provider: 'Microsoft',
    version: '1.0.0',
    downloads: 32150,
    rating: 4.9,
    ratingCount: 1247,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-03-15',
    capabilities: ['Mail.Read', 'Mail.Send', 'Thread Analysis', 'Action Item Extraction'],
    dataClassification: 'confidential',
    icon: 'mail',
    tags: ['work-iq', 'email', 'productivity', 'microsoft-365'],
    isInstalled: true,
    isWorkIQ: true,
    workIQService: 'mail',
    adminConsentRequired: true,
  },
  {
    id: 'workiq-calendar-mcp',
    name: 'Work IQ Calendar',
    description: 'Create, read, update calendar events — meeting prep, schedule optimization, and conflict detection powered by Work IQ',
    shortDescription: 'Calendar via Graph + Work IQ',
    category: 'Productivity',
    provider: 'Microsoft',
    version: '1.0.0',
    downloads: 28430,
    rating: 4.8,
    ratingCount: 986,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-03-15',
    capabilities: ['Events.ReadWrite', 'Schedule Analysis', 'Conflict Detection', 'Meeting Prep'],
    dataClassification: 'internal',
    icon: 'calendar',
    tags: ['work-iq', 'calendar', 'meetings', 'microsoft-365'],
    isInstalled: true,
    isWorkIQ: true,
    workIQService: 'calendar',
    adminConsentRequired: true,
  },
  {
    id: 'workiq-teams-mcp',
    name: 'Work IQ Teams',
    description: 'Teams channel intelligence with conversation summarization, activity tracking, and collaboration insights',
    shortDescription: 'Teams intelligence via Work IQ',
    category: 'Productivity',
    provider: 'Microsoft',
    version: '1.0.0',
    downloads: 24890,
    rating: 4.7,
    ratingCount: 856,
    status: 'pending',
    complianceLevel: 'high',
    lastUpdated: '2026-03-15',
    capabilities: ['Channel Summarization', 'Activity Tracking', 'Mention Detection', 'Collaboration Insights'],
    dataClassification: 'internal',
    icon: 'users',
    tags: ['work-iq', 'teams', 'collaboration', 'microsoft-365'],
    isInstalled: false,
    isWorkIQ: true,
    workIQService: 'teams',
    adminConsentRequired: true,
  },
  {
    id: 'workiq-sharepoint-mcp',
    name: 'Work IQ SharePoint',
    description: 'Access SharePoint sites, document libraries, lists, and metadata — permissions-aware search across files and pages with version tracking',
    shortDescription: 'SharePoint files, lists & search',
    category: 'Productivity',
    provider: 'Microsoft',
    version: '1.0.0',
    downloads: 19670,
    rating: 4.6,
    ratingCount: 723,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-03-15',
    capabilities: ['File Access', 'List Queries', 'Metadata Search', 'Version Tracking'],
    dataClassification: 'confidential',
    icon: 'file-text',
    tags: ['work-iq', 'sharepoint', 'documents', 'files', 'microsoft-365'],
    isInstalled: true,
    isWorkIQ: true,
    workIQService: 'sharepoint',
    adminConsentRequired: true,
  },
  {
    id: 'semantic-search-mcp',
    name: 'Semantic Search',
    description: 'The enterprise search substrate — AI-powered vector search that unifies discovery across Work IQ data (mail, calendar, teams, SharePoint), Dataverse CRM records, Microsoft Graph, and third-party sources into a single semantic query layer',
    shortDescription: 'Unified enterprise semantic search',
    category: 'AI/ML',
    provider: 'Microsoft',
    version: '1.0.0',
    downloads: 21450,
    rating: 4.9,
    ratingCount: 876,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-03-25',
    capabilities: ['Vector Search', 'Cross-Source Queries', 'Relevance Ranking', 'Entity Extraction', 'RAG Retrieval'],
    dataClassification: 'confidential',
    icon: 'search',
    tags: ['semantic-search', 'vector', 'ai', 'search', 'rag', 'enterprise-search'],
    isInstalled: true,
    adminConsentRequired: true,
  },
  {
    id: 'dataverse-mcp',
    name: 'Dataverse & Dynamics 365',
    description: 'The official MCP server for Dataverse — CRUD on standard and custom tables, Dynamics 365 Sales/Service entities (leads, contacts, opportunities, cases), and Dataverse custom APIs',
    shortDescription: 'Dataverse tables & D365 entities',
    category: 'CRM',
    provider: 'Microsoft',
    version: '1.0.0',
    downloads: 18750,
    rating: 4.8,
    ratingCount: 645,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-03-20',
    capabilities: ['CRUD Operations', 'Leads & Contacts', 'Opportunities', 'Custom Tables'],
    dataClassification: 'confidential',
    icon: 'database',
    tags: ['dataverse', 'dynamics-365', 'crm', 'microsoft'],
    isInstalled: true,
    adminConsentRequired: true,
  },
  {
    id: 'graph-api-mcp',
    name: 'Microsoft Graph',
    description: 'Direct access to Microsoft Graph APIs — user profiles, org directory, Planner tasks, security groups, and cross-tenant queries not covered by Work IQ MCP servers',
    shortDescription: 'Graph API for directory & tasks',
    category: 'Productivity',
    provider: 'Microsoft',
    version: '1.0.0',
    downloads: 24300,
    rating: 4.9,
    ratingCount: 1120,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-03-22',
    capabilities: ['User Profiles', 'Directory Queries', 'Planner Tasks', 'Cross-Service Search'],
    dataClassification: 'confidential',
    icon: 'share-2',
    tags: ['graph-api', 'microsoft-365', 'directory', 'users'],
    isInstalled: true,
    adminConsentRequired: true,
  },
]

export const mcpData = mcpServers

export const agentData: Agent[] = [
  {
    id: 'provisioning-agent',
    name: 'Provisioning Agent',
    description: 'Handles cloud infrastructure provisioning requests across multi-cloud environments',
    status: 'active',
    department: 'Cloud Platform',
    skills: [
      { id: 's1', name: 'Cloud Provisioning', description: 'Provision VMs and resources', mcpId: 'neon-mcp', mcpName: 'Neon', category: 'Database', isActive: true, version: '2.1.0' },
      { id: 's2', name: 'Log Analytics', description: 'Analyze application logs', mcpId: 'axiom-mcp', mcpName: 'Axiom', category: 'Logging', isActive: true, version: '1.4.0' },
    ],
    mcpConnections: ['neon-mcp', 'axiom-mcp'],
    createdAt: '2025-08-15',
    lastActive: '2026-02-03',
    requestsHandled: 15234,
    successRate: 98.5,
    icon: 'server',
    blueprintId: 'bp-cloud-ops',
    lifecycleStatus: 'active',
    observabilityEnabled: true,
    entraIdentity: {
      objectId: 'mock-entra-00000001-0000-0000-0000-000000000001',
      appId: 'mock-app-00000001-0000-0000-0000-000000000001',
      tenantId: 'mock-tenant-contoso-demo',
      mailbox: 'provisioning-agent@contoso.onmicrosoft.com',
      permissions: [
        { mcpId: 'neon-mcp', scopes: ['Database.ReadWrite', 'Schema.Manage'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'axiom-mcp', scopes: ['Logs.Read', 'Queries.Execute'], consentType: 'admin', consentStatus: 'granted' },
      ],
    },
  },
  {
    id: 'compliance-agent',
    name: 'Compliance Agent',
    description: 'Monitors and enforces compliance policies across all systems',
    status: 'active',
    department: 'Risk & Compliance',
    skills: [
      { id: 's3', name: 'Log Analysis', description: 'Analyze security logs', mcpId: 'betterstack-mcp', mcpName: 'Better Stack', category: 'Logging', isActive: true, version: '1.2.0' },
      { id: 's4', name: 'Database Monitoring', description: 'Monitor database health', mcpId: 'mongodb-mcp', mcpName: 'MongoDB Atlas', category: 'Database', isActive: true, version: '1.0.0' },
    ],
    mcpConnections: ['betterstack-mcp', 'mongodb-mcp'],
    createdAt: '2025-09-20',
    lastActive: '2026-02-03',
    requestsHandled: 8976,
    successRate: 99.2,
    icon: 'shield',
    blueprintId: 'bp-compliance',
    lifecycleStatus: 'active',
    observabilityEnabled: true,
    entraIdentity: {
      objectId: 'mock-entra-00000002-0000-0000-0000-000000000002',
      appId: 'mock-app-00000002-0000-0000-0000-000000000002',
      tenantId: 'mock-tenant-contoso-demo',
      mailbox: 'compliance-agent@contoso.onmicrosoft.com',
      permissions: [
        { mcpId: 'betterstack-mcp', scopes: ['Logs.Read', 'Alerts.Read'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'mongodb-mcp', scopes: ['Database.Read', 'Metrics.Read'], consentType: 'admin', consentStatus: 'granted' },
      ],
    },
  },
  {
    id: 'devops-agent',
    name: 'DevOps Assistant',
    description: 'Automates CI/CD pipelines and deployment workflows',
    status: 'active',
    department: 'Engineering',
    skills: [
      { id: 's5', name: 'Code Management', description: 'Manage repositories and PRs', mcpId: 'github-mcp', mcpName: 'GitHub', category: 'DevTools', isActive: true, version: '3.0.0' },
      { id: 's6', name: 'Monitoring', description: 'Monitor application health', mcpId: 'axiom-mcp', mcpName: 'Axiom', category: 'Logging', isActive: false, version: '1.4.0' },
    ],
    mcpConnections: ['github-mcp'],
    createdAt: '2025-10-05',
    lastActive: '2026-02-02',
    requestsHandled: 12456,
    successRate: 97.8,
    icon: 'git-branch',
    blueprintId: 'bp-cloud-ops',
    lifecycleStatus: 'active',
    observabilityEnabled: true,
    entraIdentity: {
      objectId: 'mock-entra-00000003-0000-0000-0000-000000000003',
      appId: 'mock-app-00000003-0000-0000-0000-000000000003',
      tenantId: 'mock-tenant-contoso-demo',
      mailbox: 'devops-agent@contoso.onmicrosoft.com',
      permissions: [
        { mcpId: 'github-mcp', scopes: ['Repos.ReadWrite', 'Actions.Manage', 'PullRequests.ReadWrite'], consentType: 'admin', consentStatus: 'granted' },
      ],
    },
  },
  {
    id: 'support-agent',
    name: 'IT Support Agent',
    description: 'Handles IT support tickets and service requests',
    status: 'active',
    department: 'IT Operations',
    skills: [
      { id: 's7', name: 'Log Search', description: 'Search and filter logs', mcpId: 'logflare-mcp', mcpName: 'Logflare', category: 'Logging', isActive: true, version: '1.1.0' },
      { id: 's8', name: 'Analytics', description: 'Track web analytics', mcpId: 'vercel-mcp', mcpName: 'Vercel Analytics', category: 'Analytics', isActive: true, version: '1.0.0' },
    ],
    mcpConnections: ['logflare-mcp', 'vercel-mcp'],
    createdAt: '2025-11-12',
    lastActive: '2026-02-03',
    requestsHandled: 23456,
    successRate: 96.4,
    icon: 'headphones',
    blueprintId: 'bp-cloud-ops',
    lifecycleStatus: 'active',
    observabilityEnabled: true,
    entraIdentity: {
      objectId: 'mock-entra-00000004-0000-0000-0000-000000000004',
      appId: 'mock-app-00000004-0000-0000-0000-000000000004',
      tenantId: 'mock-tenant-contoso-demo',
      mailbox: 'support-agent@contoso.onmicrosoft.com',
      permissions: [
        { mcpId: 'logflare-mcp', scopes: ['Logs.Read', 'Search.Execute'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'vercel-mcp', scopes: ['Analytics.Read'], consentType: 'user', consentStatus: 'granted' },
      ],
    },
  },
  {
    id: 'data-agent',
    name: 'Data Analytics Agent',
    description: 'Performs data analysis and generates insights from various data sources',
    status: 'training',
    department: 'Data Platform',
    skills: [
      { id: 's9', name: 'Data Queries', description: 'Query Postgres databases', mcpId: 'supabase-mcp', mcpName: 'Supabase', category: 'Database', isActive: false, version: '0.9.0' },
      { id: 's10', name: 'Log Insights', description: 'Generate insights from logs', mcpId: 'sematext-mcp', mcpName: 'Sematext Logs', category: 'Logging', isActive: true, version: '1.0.0' },
    ],
    mcpConnections: ['supabase-mcp'],
    createdAt: '2026-01-08',
    lastActive: '2026-02-01',
    requestsHandled: 1234,
    successRate: 94.2,
    icon: 'bar-chart',
    blueprintId: 'bp-cloud-ops',
    lifecycleStatus: 'active',
    observabilityEnabled: false,
  },
  {
    id: 'compliance-sentinel',
    name: 'Compliance Sentinel',
    description: 'Advanced compliance monitoring agent with real-time threat detection and automated policy enforcement across all environments',
    status: 'active',
    department: 'Risk & Compliance',
    skills: [
      { id: 's11', name: 'Compliance Scanning', description: 'Automated compliance scanning across systems', mcpId: 'betterstack-mcp', mcpName: 'Better Stack', category: 'Logging', isActive: true, version: '2.0.0' },
      { id: 's12', name: 'Policy Enforcement', description: 'Automated policy enforcement and violation detection', mcpId: 'mongodb-mcp', mcpName: 'MongoDB Atlas', category: 'Database', isActive: true, version: '1.5.0' },
    ],
    mcpConnections: ['betterstack-mcp', 'mongodb-mcp'],
    createdAt: '2026-01-20',
    lastActive: '2026-03-31',
    requestsHandled: 5678,
    successRate: 99.5,
    icon: 'shield-check',
    blueprintId: 'bp-compliance',
    lifecycleStatus: 'active',
    observabilityEnabled: true,
    entraIdentity: {
      objectId: 'mock-entra-00000006-0000-0000-0000-000000000006',
      appId: 'mock-app-00000006-0000-0000-0000-000000000006',
      tenantId: 'mock-tenant-contoso-demo',
      mailbox: 'compliance-sentinel@contoso.onmicrosoft.com',
      permissions: [
        { mcpId: 'betterstack-mcp', scopes: ['Logs.Read', 'Alerts.Manage', 'Compliance.Scan'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'mongodb-mcp', scopes: ['Database.Read', 'Audit.Read'], consentType: 'admin', consentStatus: 'granted' },
      ],
    },
  },
  {
    id: 'knowledge-worker-agent',
    name: 'Knowledge Worker Agent',
    description: 'Productivity agent powered by Work IQ that helps knowledge workers with email management, meeting preparation, and document insights',
    status: 'active',
    department: 'IT Operations',
    skills: [
      { id: 's13', name: 'Email Summarization', description: 'Summarize email threads and extract action items', mcpId: 'workiq-mail-mcp', mcpName: 'Work IQ Mail', category: 'Productivity', isActive: true, version: '1.0.0' },
      { id: 's14', name: 'Meeting Prep', description: 'Prepare meeting briefs and agenda summaries', mcpId: 'workiq-calendar-mcp', mcpName: 'Work IQ Calendar', category: 'Productivity', isActive: true, version: '1.0.0' },
      { id: 's15', name: 'Document Insights', description: 'Extract insights and summaries from SharePoint documents', mcpId: 'workiq-sharepoint-mcp', mcpName: 'Work IQ SharePoint', category: 'Productivity', isActive: true, version: '1.0.0' },
    ],
    mcpConnections: ['workiq-mail-mcp', 'workiq-calendar-mcp', 'workiq-sharepoint-mcp', 'semantic-search-mcp'],
    createdAt: '2026-02-01',
    lastActive: '2026-03-31',
    requestsHandled: 8945,
    successRate: 97.1,
    icon: 'brain',
    blueprintId: 'bp-knowledge-worker',
    lifecycleStatus: 'active',
    observabilityEnabled: true,
    notificationChannels: ['teams', 'outlook'],
    entraIdentity: {
      objectId: 'mock-entra-00000007-0000-0000-0000-000000000007',
      appId: 'mock-app-00000007-0000-0000-0000-000000000007',
      tenantId: 'mock-tenant-contoso-demo',
      mailbox: 'knowledge-worker@contoso.onmicrosoft.com',
      permissions: [
        { mcpId: 'workiq-mail-mcp', scopes: ['Mail.Read', 'Mail.ReadBasic'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'workiq-calendar-mcp', scopes: ['Calendars.Read', 'Calendars.ReadBasic'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'workiq-sharepoint-mcp', scopes: ['Sites.Read.All', 'Files.Read'], consentType: 'admin', consentStatus: 'granted' },
      ],
    },
  },
  {
    id: 'hr-onboarding-agent',
    name: 'HR Onboarding Agent',
    description: 'Automates new hire onboarding workflows including welcome emails, document generation, and system access provisioning',
    status: 'training',
    department: 'Human Resources',
    skills: [
      { id: 's16', name: 'Onboarding Workflow', description: 'Automated onboarding task management and welcome communications', mcpId: 'workiq-mail-mcp', mcpName: 'Work IQ Mail', category: 'Productivity', isActive: true, version: '0.9.0' },
      { id: 's17', name: 'Document Generation', description: 'Generate onboarding documents from SharePoint templates', mcpId: 'workiq-sharepoint-mcp', mcpName: 'Work IQ SharePoint', category: 'Productivity', isActive: false, version: '0.8.0' },
    ],
    mcpConnections: ['workiq-mail-mcp', 'workiq-sharepoint-mcp', 'supabase-mcp'],
    createdAt: '2026-02-15',
    lastActive: '2026-03-30',
    requestsHandled: 342,
    successRate: 92.8,
    icon: 'user-plus',
    blueprintId: 'bp-hr-onboarding',
    lifecycleStatus: 'review',
    observabilityEnabled: true,
    notificationChannels: ['outlook'],
    entraIdentity: {
      objectId: 'mock-entra-00000008-0000-0000-0000-000000000008',
      appId: 'mock-app-00000008-0000-0000-0000-000000000008',
      tenantId: 'mock-tenant-contoso-demo',
      mailbox: 'hr-onboarding@contoso.onmicrosoft.com',
      permissions: [
        { mcpId: 'workiq-mail-mcp', scopes: ['Mail.Send', 'Mail.ReadWrite'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'workiq-sharepoint-mcp', scopes: ['Sites.ReadWrite.All', 'Files.ReadWrite'], consentType: 'admin', consentStatus: 'pending' },
        { mcpId: 'supabase-mcp', scopes: ['Database.ReadWrite'], consentType: 'admin', consentStatus: 'granted' },
      ],
    },
  },
  {
    id: 'sales-rep-agent',
    name: 'Sales Rep Agent',
    description: 'Manages sales pipeline, qualifies leads, logs activities, and syncs meeting outcomes to CRM opportunities via Work IQ integration',
    status: 'active',
    department: 'Sales',
    skills: [
      { id: 's18', name: 'Pipeline Management', description: 'Visualize deal stages, move opportunities through pipeline, flag stalled deals', mcpId: 'dataverse-mcp', mcpName: 'Dataverse & Dynamics 365', category: 'CRM', isActive: true, version: '1.0.0' },
      { id: 's19', name: 'Activity Logging', description: 'Track and log sales activities to contact/opportunity timelines', mcpId: 'dataverse-mcp', mcpName: 'Dataverse & Dynamics 365', category: 'CRM', isActive: true, version: '1.0.0' },
      { id: 's20', name: 'Meeting-to-CRM Sync', description: 'Auto-log meeting notes and outcomes from Work IQ Calendar to CRM opportunities', mcpId: 'workiq-calendar-mcp', mcpName: 'Work IQ Calendar', category: 'Productivity', isActive: true, version: '1.0.0' },
      { id: 's21', name: 'Conversation Intelligence', description: 'Analyze call/email engagement patterns, extract action items, score sentiment', mcpId: 'graph-api-mcp', mcpName: 'Microsoft Graph', category: 'CRM', isActive: true, version: '1.0.0' },
    ],
    mcpConnections: ['dataverse-mcp', 'graph-api-mcp', 'workiq-mail-mcp', 'workiq-calendar-mcp', 'semantic-search-mcp'],
    createdAt: '2026-02-10',
    lastActive: '2026-03-31',
    requestsHandled: 11230,
    successRate: 97.3,
    icon: 'briefcase',
    blueprintId: 'bp-sales-ops',
    lifecycleStatus: 'active',
    observabilityEnabled: true,
    notificationChannels: ['teams', 'outlook'],
    entraIdentity: {
      objectId: 'mock-entra-00000009-0000-0000-0000-000000000009',
      appId: 'mock-app-00000009-0000-0000-0000-000000000009',
      tenantId: 'mock-tenant-contoso-demo',
      mailbox: 'sales-rep-agent@contoso.onmicrosoft.com',
      permissions: [
        { mcpId: 'dataverse-mcp', scopes: ['Leads.ReadWrite', 'Contacts.ReadWrite', 'Opportunities.ReadWrite'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'graph-api-mcp', scopes: ['Conversations.Read', 'Engagement.Read'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'workiq-mail-mcp', scopes: ['Mail.Read', 'Mail.Send'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'workiq-calendar-mcp', scopes: ['Calendars.Read', 'Events.Read'], consentType: 'admin', consentStatus: 'granted' },
      ],
    },
  },
  {
    id: 'sales-manager-agent',
    name: 'Sales Manager Agent',
    description: 'Monitors team pipeline health, generates revenue forecasts, tracks deal velocity, and posts pipeline updates to Teams channels',
    status: 'active',
    department: 'Sales',
    skills: [
      { id: 's22', name: 'Revenue Forecasting', description: 'Generate quarterly/annual forecasts from pipeline data with confidence scoring', mcpId: 'dataverse-mcp', mcpName: 'Dataverse & Dynamics 365', category: 'CRM', isActive: true, version: '1.0.0' },
      { id: 's23', name: 'Pipeline Management', description: 'Monitor team pipeline health, identify bottlenecks, track deal velocity', mcpId: 'dataverse-mcp', mcpName: 'Dataverse & Dynamics 365', category: 'CRM', isActive: true, version: '1.0.0' },
    ],
    mcpConnections: ['dataverse-mcp', 'graph-api-mcp', 'workiq-teams-mcp', 'semantic-search-mcp'],
    createdAt: '2026-02-15',
    lastActive: '2026-03-31',
    requestsHandled: 6780,
    successRate: 98.1,
    icon: 'bar-chart',
    blueprintId: 'bp-sales-ops',
    lifecycleStatus: 'active',
    observabilityEnabled: true,
    notificationChannels: ['teams'],
    entraIdentity: {
      objectId: 'mock-entra-00000010-0000-0000-0000-000000000010',
      appId: 'mock-app-00000010-0000-0000-0000-000000000010',
      tenantId: 'mock-tenant-contoso-demo',
      mailbox: 'sales-manager@contoso.onmicrosoft.com',
      permissions: [
        { mcpId: 'dataverse-mcp', scopes: ['Leads.Read', 'Contacts.Read', 'Opportunities.Read', 'Pipeline.Read'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'dataverse-mcp', scopes: ['Forecasts.ReadWrite', 'Quotas.Read', 'Analytics.Read'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'workiq-teams-mcp', scopes: ['Channels.ReadWrite', 'Messages.Send'], consentType: 'admin', consentStatus: 'granted' },
      ],
    },
  },
  {
    id: 'lead-gen-agent',
    name: 'Lead Generation Agent',
    description: 'Scores and qualifies leads, enriches contact profiles from email and Teams signals, and tracks prospect engagement',
    status: 'active',
    department: 'Marketing',
    skills: [
      { id: 's24', name: 'Contact Enrichment', description: 'Enrich contact profiles from email and Teams signals using Work IQ data', mcpId: 'graph-api-mcp', mcpName: 'Microsoft Graph', category: 'CRM', isActive: true, version: '1.0.0' },
      { id: 's25', name: 'Activity Logging', description: 'Track prospect engagement activities and log to CRM', mcpId: 'dataverse-mcp', mcpName: 'Dataverse & Dynamics 365', category: 'CRM', isActive: true, version: '1.0.0' },
      { id: 's26', name: 'Conversation Intelligence', description: 'Analyze prospect email engagement and extract buying signals', mcpId: 'graph-api-mcp', mcpName: 'Microsoft Graph', category: 'CRM', isActive: true, version: '1.0.0' },
    ],
    mcpConnections: ['dataverse-mcp', 'graph-api-mcp', 'workiq-mail-mcp', 'semantic-search-mcp'],
    createdAt: '2026-03-01',
    lastActive: '2026-03-31',
    requestsHandled: 4560,
    successRate: 96.8,
    icon: 'target',
    blueprintId: 'bp-sales-ops',
    lifecycleStatus: 'active',
    observabilityEnabled: true,
    notificationChannels: ['outlook'],
    entraIdentity: {
      objectId: 'mock-entra-00000011-0000-0000-0000-000000000011',
      appId: 'mock-app-00000011-0000-0000-0000-000000000011',
      tenantId: 'mock-tenant-contoso-demo',
      mailbox: 'lead-gen-agent@contoso.onmicrosoft.com',
      permissions: [
        { mcpId: 'dataverse-mcp', scopes: ['Leads.ReadWrite', 'Contacts.ReadWrite'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'graph-api-mcp', scopes: ['Conversations.Read', 'Engagement.Read', 'RelationshipHealth.Read'], consentType: 'admin', consentStatus: 'granted' },
        { mcpId: 'workiq-mail-mcp', scopes: ['Mail.Read'], consentType: 'admin', consentStatus: 'granted' },
      ],
    },
  },
]

export const governancePolicies: GovernancePolicy[] = [
  {
    id: 'pol-1',
    name: 'Data Classification Policy',
    description: 'Enforces data access controls based on classification levels',
    rules: [
      { id: 'r1', type: 'data-access', condition: 'classification == restricted', action: 'require_approval' },
      { id: 'r2', type: 'data-access', condition: 'classification == confidential', action: 'log_access' },
    ],
    appliedTo: ['neon-mcp', 'supabase-mcp', 'mongodb-mcp'],
    status: 'active',
    createdBy: 'Security Team',
    createdAt: '2025-06-15',
  },
  {
    id: 'pol-2',
    name: 'Rate Limiting Policy',
    description: 'Controls API request rates to prevent abuse',
    rules: [
      { id: 'r3', type: 'rate-limit', condition: 'requests_per_minute > 1000', action: 'throttle' },
      { id: 'r4', type: 'rate-limit', condition: 'requests_per_minute > 5000', action: 'block' },
    ],
    appliedTo: ['github-mcp', 'axiom-mcp'],
    status: 'active',
    createdBy: 'Platform Team',
    createdAt: '2025-07-20',
  },
  {
    id: 'pol-3',
    name: 'Compliance Verification',
    description: 'Requires compliance checks before MCP registration',
    rules: [
      { id: 'r5', type: 'compliance', condition: 'has_security_review == false', action: 'block_registration' },
      { id: 'r6', type: 'compliance', condition: 'has_data_classification == false', action: 'require_classification' },
    ],
    appliedTo: ['all'],
    status: 'active',
    createdBy: 'Compliance Team',
    createdAt: '2025-08-10',
  },
]

