import type { MCP, Agent, GovernancePolicy } from './types'

export const mcpCategories = [
  'All Categories',
  'AI',
  'Analytics',
  'Database',
  'DevTools',
  'Infrastructure',
  'Logging',
  'Monitoring',
  'Observability',
  'Security',
  'Storage',
] as const

// Map for backwards compatibility
export const mcpServers: MCP[] = [
  {
    id: 'axiom-mcp',
    name: 'Axiom',
    description: 'Logs, functions, and Web Vitals insights for full-stack observability',
    shortDescription: 'Full-stack observability platform',
    category: 'Logging',
    provider: 'Axiom',
    version: '2.4.1',
    downloads: 15420,
    rating: 4.8,
    ratingCount: 342,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-01-28',
    capabilities: ['Log Ingestion', 'Query Analytics', 'Dashboards', 'Alerting'],
    dataClassification: 'internal',
    icon: 'activity',
    tags: ['logging', 'observability', 'analytics', 'monitoring'],
    isInstalled: true,
  },
  {
    id: 'baseline-mcp',
    name: 'Baseline',
    description: 'Search, query and alert on application logs with intelligent filtering',
    shortDescription: 'Log search and alerting',
    category: 'Logging',
    provider: 'Baseline',
    version: '3.1.0',
    downloads: 8932,
    rating: 4.9,
    ratingCount: 287,
    status: 'pending',
    complianceLevel: 'high',
    lastUpdated: '2026-01-25',
    capabilities: ['Log Search', 'Alerting', 'Dashboards', 'Integrations'],
    dataClassification: 'confidential',
    icon: 'search',
    tags: ['logging', 'search', 'alerts', 'monitoring'],
    isInstalled: false,
  },
  {
    id: 'betterstack-mcp',
    name: 'Better Stack',
    description: 'Query logs like you query your database with powerful SQL-like syntax',
    shortDescription: 'SQL-powered log querying',
    category: 'Logging',
    provider: 'Better Stack',
    version: '1.8.2',
    downloads: 12543,
    rating: 4.7,
    ratingCount: 198,
    status: 'active',
    complianceLevel: 'medium',
    lastUpdated: '2026-01-30',
    capabilities: ['SQL Queries', 'Log Analytics', 'Uptime Monitoring', 'Incident Management'],
    dataClassification: 'internal',
    icon: 'terminal',
    tags: ['logging', 'sql', 'uptime', 'incidents'],
    isInstalled: true,
  },
  {
    id: 'graphjson-mcp',
    name: 'GraphJSON',
    description: 'Slice, dice and visualize your logs with interactive graph interfaces',
    shortDescription: 'Visual log exploration',
    category: 'Logging',
    provider: 'GraphJSON',
    version: '2.2.0',
    downloads: 9876,
    rating: 4.6,
    ratingCount: 156,
    status: 'pending',
    complianceLevel: 'medium',
    lastUpdated: '2026-01-22',
    capabilities: ['Visualization', 'JSON Parsing', 'Graph Analytics', 'Export'],
    dataClassification: 'internal',
    icon: 'bar-chart',
    tags: ['visualization', 'json', 'graphs', 'analytics'],
    isInstalled: false,
  },
  {
    id: 'logalert-mcp',
    name: 'Logalert',
    description: 'Easily set up alerts from your logs with intelligent anomaly detection',
    shortDescription: 'Smart log alerting',
    category: 'Logging',
    provider: 'Logalert',
    version: '4.0.1',
    downloads: 18234,
    rating: 4.8,
    ratingCount: 423,
    status: 'pending',
    complianceLevel: 'high',
    lastUpdated: '2026-01-29',
    capabilities: ['Anomaly Detection', 'Custom Alerts', 'Integrations', 'Escalation'],
    dataClassification: 'internal',
    icon: 'bell',
    tags: ['alerts', 'anomaly', 'notifications', 'monitoring'],
    isInstalled: false,
  },
  {
    id: 'logflare-mcp',
    name: 'Logflare',
    description: 'Search, charts and alerts for logs with real-time streaming',
    shortDescription: 'Real-time log streaming',
    category: 'Logging',
    provider: 'Logflare',
    version: '1.5.3',
    downloads: 7654,
    rating: 4.5,
    ratingCount: 134,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-01-20',
    capabilities: ['Streaming', 'Search', 'Charts', 'Alerts'],
    dataClassification: 'confidential',
    icon: 'zap',
    tags: ['streaming', 'real-time', 'search', 'charts'],
    isInstalled: false,
  },
  {
    id: 'sematext-mcp',
    name: 'Sematext Logs',
    description: 'Send logs to Sematext for easy debugging and comprehensive analysis',
    shortDescription: 'Log debugging and analysis',
    category: 'Logging',
    provider: 'Sematext',
    version: '2.1.0',
    downloads: 21345,
    rating: 4.7,
    ratingCount: 512,
    status: 'pending',
    complianceLevel: 'medium',
    lastUpdated: '2026-01-27',
    capabilities: ['Log Collection', 'Debugging', 'Analysis', 'Correlation'],
    dataClassification: 'internal',
    icon: 'file-text',
    tags: ['logging', 'debugging', 'analysis', 'apm'],
    isInstalled: false,
  },
  {
    id: 'mongodb-mcp',
    name: 'MongoDB Atlas',
    description: 'Connect and query MongoDB collections with intelligent context awareness',
    shortDescription: 'MongoDB database integration',
    category: 'Database',
    provider: 'MongoDB',
    version: '3.0.2',
    downloads: 11234,
    rating: 4.9,
    ratingCount: 289,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-01-26',
    capabilities: ['Queries', 'Aggregation', 'Indexing', 'Atlas Search'],
    dataClassification: 'confidential',
    icon: 'database',
    tags: ['mongodb', 'database', 'nosql', 'atlas'],
    isInstalled: true,
  },
  {
    id: 'github-mcp',
    name: 'GitHub',
    description: 'Interact with GitHub repositories for automation, insights, and code intelligence',
    shortDescription: 'GitHub repository integration',
    category: 'DevTools',
    provider: 'GitHub',
    version: '2.0.0',
    downloads: 25678,
    rating: 4.8,
    ratingCount: 634,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-01-31',
    capabilities: ['Repository Management', 'Pull Requests', 'Issues', 'Actions'],
    dataClassification: 'confidential',
    icon: 'git-branch',
    tags: ['github', 'git', 'code', 'repositories'],
    isInstalled: true,
  },
  {
    id: 'vercel-mcp',
    name: 'Vercel Analytics',
    description: 'Privacy-friendly, first-party analytics for web applications',
    shortDescription: 'Web analytics platform',
    category: 'Analytics',
    provider: 'Vercel',
    version: '1.2.1',
    downloads: 4532,
    rating: 4.4,
    ratingCount: 87,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-01-18',
    capabilities: ['Page Views', 'Web Vitals', 'Custom Events', 'Funnels'],
    dataClassification: 'restricted',
    icon: 'trending-up',
    tags: ['analytics', 'web-vitals', 'performance', 'vercel'],
    isInstalled: true,
  },
  {
    id: 'supabase-mcp',
    name: 'Supabase',
    description: 'Open source Firebase alternative with Postgres database and auth',
    shortDescription: 'Backend-as-a-service',
    category: 'Database',
    provider: 'Supabase',
    version: '1.9.0',
    downloads: 16789,
    rating: 4.6,
    ratingCount: 378,
    status: 'active',
    complianceLevel: 'medium',
    lastUpdated: '2026-01-24',
    capabilities: ['Database', 'Authentication', 'Storage', 'Edge Functions'],
    dataClassification: 'internal',
    icon: 'database',
    tags: ['supabase', 'postgres', 'auth', 'storage'],
    isInstalled: false,
  },
  {
    id: 'neon-mcp',
    name: 'Neon',
    description: 'Serverless Postgres with branching, autoscaling, and bottomless storage',
    shortDescription: 'Serverless Postgres',
    category: 'Database',
    provider: 'Neon',
    version: '2.3.1',
    downloads: 13456,
    rating: 4.7,
    ratingCount: 298,
    status: 'active',
    complianceLevel: 'high',
    lastUpdated: '2026-01-23',
    capabilities: ['Branching', 'Autoscaling', 'Point-in-time Recovery', 'Connection Pooling'],
    dataClassification: 'confidential',
    icon: 'database',
    tags: ['postgres', 'serverless', 'database', 'neon'],
    isInstalled: false,
  },
]

export const mcpData = mcpServers

export const agentData: Agent[] = [
  {
    id: 'provisioning-agent',
    name: 'Provisioning Agent',
    description: 'Handles cloud infrastructure provisioning requests across multi-cloud environments',
    status: 'active',
    department: 'Cloud Platform',
    skills: [
      { id: 's1', name: 'Cloud Provisioning', description: 'Provision VMs and resources', mcpId: 'neon-mcp', mcpName: 'Neon', category: 'Database', isActive: true },
      { id: 's2', name: 'Log Analytics', description: 'Analyze application logs', mcpId: 'axiom-mcp', mcpName: 'Axiom', category: 'Logging', isActive: true },
    ],
    mcpConnections: ['neon-mcp', 'axiom-mcp'],
    createdAt: '2025-08-15',
    lastActive: '2026-02-03',
    requestsHandled: 15234,
    successRate: 98.5,
    icon: 'server',
  },
  {
    id: 'compliance-agent',
    name: 'Compliance Agent',
    description: 'Monitors and enforces compliance policies across all systems',
    status: 'active',
    department: 'Risk & Compliance',
    skills: [
      { id: 's3', name: 'Log Analysis', description: 'Analyze security logs', mcpId: 'betterstack-mcp', mcpName: 'Better Stack', category: 'Logging', isActive: true },
      { id: 's4', name: 'Database Monitoring', description: 'Monitor database health', mcpId: 'mongodb-mcp', mcpName: 'MongoDB Atlas', category: 'Database', isActive: true },
    ],
    mcpConnections: ['betterstack-mcp', 'mongodb-mcp'],
    createdAt: '2025-09-20',
    lastActive: '2026-02-03',
    requestsHandled: 8976,
    successRate: 99.2,
    icon: 'shield',
  },
  {
    id: 'devops-agent',
    name: 'DevOps Assistant',
    description: 'Automates CI/CD pipelines and deployment workflows',
    status: 'active',
    department: 'Engineering',
    skills: [
      { id: 's5', name: 'Code Management', description: 'Manage repositories and PRs', mcpId: 'github-mcp', mcpName: 'GitHub', category: 'DevTools', isActive: true },
      { id: 's6', name: 'Monitoring', description: 'Monitor application health', mcpId: 'axiom-mcp', mcpName: 'Axiom', category: 'Logging', isActive: false },
    ],
    mcpConnections: ['github-mcp'],
    createdAt: '2025-10-05',
    lastActive: '2026-02-02',
    requestsHandled: 12456,
    successRate: 97.8,
    icon: 'git-branch',
  },
  {
    id: 'support-agent',
    name: 'IT Support Agent',
    description: 'Handles IT support tickets and service requests',
    status: 'active',
    department: 'IT Operations',
    skills: [
      { id: 's7', name: 'Log Search', description: 'Search and filter logs', mcpId: 'logflare-mcp', mcpName: 'Logflare', category: 'Logging', isActive: true },
      { id: 's8', name: 'Analytics', description: 'Track web analytics', mcpId: 'vercel-mcp', mcpName: 'Vercel Analytics', category: 'Analytics', isActive: true },
    ],
    mcpConnections: ['logflare-mcp', 'vercel-mcp'],
    createdAt: '2025-11-12',
    lastActive: '2026-02-03',
    requestsHandled: 23456,
    successRate: 96.4,
    icon: 'headphones',
  },
  {
    id: 'data-agent',
    name: 'Data Analytics Agent',
    description: 'Performs data analysis and generates insights from various data sources',
    status: 'training',
    department: 'Data Platform',
    skills: [
      { id: 's9', name: 'Data Queries', description: 'Query Postgres databases', mcpId: 'supabase-mcp', mcpName: 'Supabase', category: 'Database', isActive: false },
      { id: 's10', name: 'Log Insights', description: 'Generate insights from logs', mcpId: 'sematext-mcp', mcpName: 'Sematext Logs', category: 'Logging', isActive: true },
    ],
    mcpConnections: ['supabase-mcp'],
    createdAt: '2026-01-08',
    lastActive: '2026-02-01',
    requestsHandled: 1234,
    successRate: 94.2,
    icon: 'bar-chart',
  },
]

export const governancePolicies: GovernancePolicy[] = [
  {
    id: 'pol-1',
    name: 'Data Classification Policy',
    description: 'Enforces data access controls based on classification levels',
    rules: [
      { id: 'r1', type: 'data-access', condition: 'classification == restricted', action: 'require_approval' },
      { id: 'r2', type: 'data-access', condition: 'classification == confidential', action: 'log_access' },
    ],
    appliedTo: ['neon-mcp', 'supabase-mcp', 'mongodb-mcp'],
    status: 'active',
    createdBy: 'Security Team',
    createdAt: '2025-06-15',
  },
  {
    id: 'pol-2',
    name: 'Rate Limiting Policy',
    description: 'Controls API request rates to prevent abuse',
    rules: [
      { id: 'r3', type: 'rate-limit', condition: 'requests_per_minute > 1000', action: 'throttle' },
      { id: 'r4', type: 'rate-limit', condition: 'requests_per_minute > 5000', action: 'block' },
    ],
    appliedTo: ['github-mcp', 'axiom-mcp'],
    status: 'active',
    createdBy: 'Platform Team',
    createdAt: '2025-07-20',
  },
  {
    id: 'pol-3',
    name: 'Compliance Verification',
    description: 'Requires compliance checks before MCP registration',
    rules: [
      { id: 'r5', type: 'compliance', condition: 'has_security_review == false', action: 'block_registration' },
      { id: 'r6', type: 'compliance', condition: 'has_data_classification == false', action: 'require_classification' },
    ],
    appliedTo: ['all'],
    status: 'active',
    createdBy: 'Compliance Team',
    createdAt: '2025-08-10',
  },
]
